/**
 * Out-of-process iframe session management.
 *
 * Discovery attaches to iframe targets, associates each child session with its
 * host IFRAME, and optionally remaps stale session IDs after navigation.
 * Tree capture runs per child session and filters failed children. Cleanup
 * detaches current targets while preserving the old-to-new ID map needed by
 * references from older DOM snapshots.
 */

import type { CDPClient } from './client';
import type { Target, DOMSnapshot, DOM, Accessibility } from '../dom/types/cdp';
import type { OOPIFTreeData } from '../dom/types/snapshot';
import { REQUIRED_COMPUTED_STYLES } from '../dom/types/snapshot';

export interface OOPIFSession {
  sessionId: string;
  targetInfo: Target.TargetInfo;
  frameId: string;
  frameUrl: string;
  /** The main tree DOM corresponds to IFRAME elements. */
  ownerBackendNodeId: number;
}

export class OOPIFManager {
  private sessions: Map<string, OOPIFSession> = new Map();
  private cdpClient: CDPClient | null = null;
  /** The old sessionId map to the current sessionId; rediscovery with the corresponding host node at ownerBackendNodeId. */
  private sessionIdRemap: Map<string, string> = new Map();

  /**
   * Found and connected to all OOPIF subs target.
   * To ensure that the discovery process is stable, calls Target.getTargets() and Target.attachToTarget () are made on their own initiative;
   * An event-based Target.setAutoAttach does not always have a reliable trigger in Electron.
   *
   * @parammode - tag: buildTree was first discovered and marked with sessionId elements.
   * `remap : Rediscover before interaction, read old tags and create a new sessionId map.
   */
  async discoverOOPIFs(
    cdpClient: CDPClient,
    mode: 'tag' | 'remap' = 'tag',
  ): Promise<OOPIFSession[]> {
    this.cdpClient = cdpClient;
    this.sessions.clear();

    try {
      // All target in the query browser is reserved only for targets generated by independent iframe.
      const { targetInfos } = await cdpClient.sendCommand<{
        targetInfos: Target.TargetInfo[];
      }>('Target.getTargets');

      const iframeTargets = targetInfos.filter(t => t.type === 'iframe');
      if (iframeTargets.length === 0) return [];


      // Connect iframe target to get their respective sub-items CDP sessionId.
      for (const targetInfo of iframeTargets) {
        try {
          const { sessionId } = await cdpClient.sendCommand<{
            sessionId: string;
          }>('Target.attachToTarget', {
            targetId: targetInfo.targetId,
            flatten: true,
          });

          const session = await this.resolveSession(
            cdpClient,
            sessionId,
            targetInfo,
            mode,
          );
          if (session) {
            this.sessions.set(session.sessionId, session);
          }
        } catch (error) {
          // Skip silently when a single iframe connection fails and continue to process other iframe connections.
        }
      }


      return [...this.sessions.values()];
    } catch (error) {
      // Returns the empty list when the whole failed to find out so that the main page DOM can continue.
      return [];
    }
  }

  private static readonly SESSION_ATTR = 'data-oopif-session';

  /**
   * Parsing a newly created pending confirmation session: find its frameId and the corresponding IFRAME host element in the main DOM.
   * The tag mode will write sessionId to iframe properties; the remap mode will read old properties and create a map of the old ID to the new ID.
   * Any failure of a key positioning step returns null, which means that this round ignores OOPIF.
   */
  private async resolveSession(
    cdpClient: CDPClient,
    sessionId: string,
    targetInfo: Target.TargetInfo,
    mode: 'tag' | 'remap',
  ): Promise<OOPIFSession | null> {
    let frameId: string;
    try {
      const frameTree = await cdpClient.sendCommand<{
        frameTree: { frame: { id: string; url: string } };
      }>('Page.getFrameTree', {}, 5000, sessionId);
      frameId = frameTree.frameTree.frame.id;
    } catch {
      // Without a frame tree, this target cannot be mapped to an OOPIF safely.
      return null;
    }

    let ownerBackendNodeId: number;
    try {
      const owner = await cdpClient.sendCommand<{
        backendNodeId: number;
        nodeId?: number;
      }>('DOM.getFrameOwner', { frameId });
      ownerBackendNodeId = owner.backendNodeId;
    } catch {
      // When it is not possible to find the host IFRAME node, skip the session silently.
      return null;
    }

    try {
      const { object } = (await cdpClient.sendCommand('DOM.resolveNode', {
        backendNodeId: ownerBackendNodeId,
      })) as { object: { objectId: string } };

      if (mode === 'tag') {
        // First found: Write the current sessionId on host iframe elements for subsequent rediscovery.
        await cdpClient.sendCommand('Runtime.callFunctionOn', {
          objectId: object.objectId,
          functionDeclaration: `function(attr, id) { this.setAttribute(attr, id); }`,
          arguments: [
            { value: OOPIFManager.SESSION_ATTR },
            { value: sessionId },
          ],
          returnByValue: true,
        });
      } else {
        // Rediscover: Read the old ID on the host node and create a new map when ID changes.
        const readResult = await cdpClient.sendCommand<{
          result?: { value?: string };
        }>('Runtime.callFunctionOn', {
          objectId: object.objectId,
          functionDeclaration: `function(attr) { return this.getAttribute(attr); }`,
          arguments: [{ value: OOPIFManager.SESSION_ATTR }],
          returnByValue: true,
        });
        const oldSessionId = readResult.result?.value;
        if (oldSessionId && oldSessionId !== sessionId) {
          this.sessionIdRemap.set(oldSessionId, sessionId);
        }
      }

      await cdpClient
        .sendCommand('Runtime.releaseObject', { objectId: object.objectId })
        .catch(() => {});
    } catch {
      // Node tags or map failures are not fatal errors; frame and host node information can still be used for tree collection on this wheel.
    }

    return {
      sessionId,
      targetInfo,
      frameId,
      frameUrl: targetInfo.url,
      ownerBackendNodeId,
    };
  }

  /**
   * All data found in OOPIF session are collected in parallel.
   * Converts a single OOPIF to null when a single OOPIF fails, filters all failed entries after completion and returns only the successful result.
   */
  async captureAllOOPIFTrees(): Promise<OOPIFTreeData[]> {
    if (!this.cdpClient || this.sessions.size === 0) {
      return [];
    }

    const results = await Promise.all(
      [...this.sessions.values()].map(session =>
        this.captureOOPIFTree(session).catch(() => {
          // A single iframe collection failure does not block other iframe or main page results.
          return null;
        }),
      ),
    );

    return results.filter((r): r is OOPIFTreeData => r !== null);
  }

  /**
   * Separate OOPIF session parallel collection of DOM snapshots, complete DOM trees and AX accessible trees.
   * The snapshot and the tree DOM are key data, and failure will cause the OOPIF to fail as a whole; the AX tree failure is allowed to fall back to an empty node array.
   */
  private async captureOOPIFTree(
    session: OOPIFSession,
  ): Promise<OOPIFTreeData> {
    const cdpClient = this.cdpClient!;
    const { sessionId } = session;

    const [snapshot, domTree, axTree] = await Promise.all([
      cdpClient.sendCommandWithRetry<DOMSnapshot.CaptureSnapshotResponse>(
        'DOMSnapshot.captureSnapshot',
        {
          computedStyles: [...REQUIRED_COMPUTED_STYLES],
          includePaintOrder: true,
          includeDOMRects: true,
          includeBlendedBackgroundColors: false,
          includeTextColorOpacities: false,
        },
        { timeout: 10000, maxRetries: 1, sessionId },
      ),
      cdpClient.sendCommand<DOM.GetDocumentResponse>(
        'DOM.getDocument',
        { depth: -1, pierce: true },
        10000,
        sessionId,
      ),
      cdpClient
        .sendCommand<Accessibility.GetFullAXTreeResponse>(
          'Accessibility.getFullAXTree',
          {},
          10000,
          sessionId,
        )
        .catch(() => ({ nodes: [] }) as Accessibility.GetFullAXTreeResponse),
    ]);

    return {
      sessionId: session.sessionId,
      frameId: session.frameId,
      frameUrl: session.frameUrl,
      ownerBackendNodeId: session.ownerBackendNodeId,
      snapshot,
      domTree,
      axTree,
    };
  }

  /**
   * Send CDP commands to specified OOPIF session.
   * The possibly expired sessionId will be automatically resolved to the current ID by a map sheet before sending.
   */
  async sendCommand<T = unknown>(
    sessionId: string,
    method: string,
    params?: Record<string, unknown>,
    timeout = 10000,
  ): Promise<T> {
    if (!this.cdpClient) {
      throw new Error('[OOPIF] Manager not initialized');
    }
    const resolvedId = this.resolveSessionId(sessionId);
    return this.cdpClient.sendCommand<T>(method, params, timeout, resolvedId);
  }

  /**
   * Converts sessionId which may have expired to the current ID; returns as it is when no map is available.
   */
  resolveSessionId(sessionId: string): string {
    return this.sessionIdRemap.get(sessionId) ?? sessionId;
  }

  /**
   * Returns all session found in the current round and converts it to a new array, avoiding the caller changing the internal Map directly.
   */
  getSessions(): OOPIFSession[] {
    return [...this.sessions.values()];
  }

  /**
   * Check if at least one OOPIF session has been found in this round.
   */
  hasOOPIFs(): boolean {
    return this.sessions.size > 0;
  }

  /**
   * Check if the manager still holds activity CDPClient, i.e. not completed cleanup.
   */
  isConnected(): boolean {
    return this.cdpClient !== null;
  }

  /**
   * Cleans up the manager and disconnects the sub target.
   * Cleanup order: detach each child target, clear current sessions, preserve the old-to-new ID remap, and release the CDPClient reference.
   */
  async cleanup(): Promise<void> {
    // Disconnect the current record item target on a case-by-case basis; one target is disconnected without prejudice to subsequent cleanup.
    if (this.cdpClient) {
      for (const [sessionId] of this.sessions) {
        try {
          await this.cdpClient.sendCommand('Target.detachFromTarget', {
            sessionId,
          });
        } catch {
          // target may have been disconnected earlier by navigation, closure or process change.
        }
      }
    }

    this.sessions.clear();
    // Keep sessionIdRemap after cleanup because the old DOM node reference may need to be used to find a new session.
    this.cdpClient = null;
  }
}
